<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!DOCTYPE MEME[
<!ELEMENT MEME (
  training_set,
  model, 
  motifs, 
  scanned_sites_summary?
)>
<!ATTLIST MEME 
  version CDATA #REQUIRED
  release CDATA #REQUIRED
>
<!-- Training-set elements -->
<!ELEMENT training_set (alphabet, ambigs, sequence*, letter_frequencies)>
<!ATTLIST training_set datafile CDATA #REQUIRED length CDATA #REQUIRED>
<!ELEMENT alphabet (letter*)>
<!ATTLIST alphabet name CDATA #REQUIRED>
<!ELEMENT ambigs (letter*)>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ATTLIST letter equals CDATA #IMPLIED>
<!ATTLIST letter aliases CDATA #IMPLIED>
<!ATTLIST letter complement CDATA #IMPLIED>
<!ATTLIST letter name CDATA #IMPLIED>
<!ATTLIST letter colour CDATA #IMPLIED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED
                   name CDATA #REQUIRED
                   length CDATA #REQUIRED
                   weight CDATA #REQUIRED
>
<!ELEMENT letter_frequencies (alphabet_array)>

<!-- Model elements -->
<!ELEMENT model (
  command_line,
  host,
  type,
  nmotifs,
  evalue_threshold,
  object_function,
  spfun,
  min_width,
  max_width,
  wg,
  ws,
  endgaps,
  minsites,
  maxsites,
  wnsites,
  spmap,
  spfuzz,
  prior,
  beta,
  maxiter,
  distance,
  num_sequences,
  num_positions,
  seed,
  hsfrac,
  maxwords,
  maxsize,
  csites,
  strands,
  priors_file,
  reason_for_stopping,
  back_order,
  background_frequencies
)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT spfun (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_sequences (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT hsfrac (#PCDATA)*>
<!ELEMENT maxwords (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT csites (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT back_order (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED>

<!-- Motif elements -->
<!ELEMENT motifs (motif*)>
<!ELEMENT motif (scores, probabilities, regular_expression?, contributing_sites)>
<!ATTLIST motif id ID #REQUIRED
                name CDATA #REQUIRED
                alt CDATA ""
                width CDATA #REQUIRED
                sites CDATA #REQUIRED
                llr CDATA #REQUIRED
                ic CDATA #REQUIRED
                re CDATA #REQUIRED
                bayes_threshold CDATA #REQUIRED
                e_value CDATA #REQUIRED
                elapsed_time CDATA #REQUIRED
                url CDATA ""
>
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>

<!-- Contributing site elements -->
<!-- Contributing sites are motif occurences found during the motif discovery phase -->
<!ELEMENT contributing_sites (contributing_site*)>
<!ELEMENT contributing_site (left_flank, site, right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED
                          position CDATA #REQUIRED
                          strand (plus|minus|none) 'none'
                          pvalue CDATA #REQUIRED
>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start -->
<!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance -->
<!ELEMENT site (letter_ref*)>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end -->
<!ELEMENT right_flank (#PCDATA)>

<!-- Scanned site elements -->
<!-- Scanned sites are motif occurences found during the sequence scan phase -->
<!ELEMENT scanned_sites_summary (scanned_sites*)>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site*)>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED
                        pvalue CDATA #REQUIRED
                        num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site  motif_id IDREF #REQUIRED
                        strand (plus|minus|none) 'none'
                        position CDATA #REQUIRED
                        pvalue CDATA #REQUIRED>

<!-- Utility elements -->
<!-- A reference to a letter in the alphabet -->
<!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet -->
<!ELEMENT alphabet_array (value*)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>

<!-- A alphabet_matrix contains one alphabet_array for each position in a motif -->
<!ELEMENT alphabet_matrix (alphabet_array*)>

]>
<!-- Begin document body -->
<MEME version="4.12.0" release="Tue Jun 27 16:22:50 2017 -0700">
<training_set datafile="gataEGca_0.1_250.cytomod.faa.memechip/seqs-centered" length="250">
<alphabet name="DNA with covalent modifications" like="dna">
<letter id="A" symbol="A" complement="T" name="Adenine" colour="8510A8"/>
<letter id="C" symbol="C" complement="G" name="Cytosine" colour="A50026"/>
<letter id="G" symbol="G" complement="C" name="Guanine" colour="313695"/>
<letter id="T" symbol="T" complement="A" name="Thymine" colour="A89610"/>
<letter id="c" symbol="c" complement="4" name="5-Carboxylcytosine" colour="FEE090"/>
<letter id="f" symbol="f" complement="3" name="5-Formylcytosine" colour="FDAE61"/>
<letter id="h" symbol="h" complement="2" name="5-Hydroxymethylcytosine" colour="F46D43"/>
<letter id="m" symbol="m" complement="1" name="5-Methylcytosine" colour="D73027"/>
<letter id="n1" symbol="1" complement="m" name="Guanine:5-Methylcytosine" colour="4575B4"/>
<letter id="n2" symbol="2" complement="h" name="Guanine:5-Hydroxymethylcytosine" colour="74ADD1"/>
<letter id="n3" symbol="3" complement="f" name="Guanine:5-Formylcytosine" colour="ABD9E9"/>
<letter id="n4" symbol="4" complement="c" name="Guanine:5-Carboxylcytosine" colour="E0F3F8"/>
<letter id="x3F" symbol="?" equals="ACGTcfhm1234"/>
<letter id="z" symbol="z" equals="Ccfhm"/>
<letter id="n9" symbol="9" equals="G1234"/>
<letter id="N" symbol="N" equals="ACGT"/>
<letter id="V" symbol="V" equals="ACG"/>
<letter id="H" symbol="H" equals="ACT"/>
<letter id="D" symbol="D" equals="AGT"/>
<letter id="B" symbol="B" equals="CGT"/>
<letter id="y" symbol="y" equals="Ccf"/>
<letter id="n8" symbol="8" equals="G34"/>
<letter id="M" symbol="M" equals="AC"/>
<letter id="R" symbol="R" equals="AG"/>
<letter id="W" symbol="W" equals="AT"/>
<letter id="S" symbol="S" equals="CG"/>
<letter id="Y" symbol="Y" equals="CT"/>
<letter id="K" symbol="K" equals="GT"/>
<letter id="x" symbol="x" equals="hm"/>
<letter id="n7" symbol="7" equals="12"/>
</alphabet>
<sequence id="sequence_0" name="0" length="100" weight="1.000000" />
<sequence id="sequence_1" name="1" length="100" weight="1.000000" />
<sequence id="sequence_2" name="2" length="100" weight="1.000000" />
<sequence id="sequence_3" name="3" length="100" weight="1.000000" />
<sequence id="sequence_4" name="4" length="100" weight="1.000000" />
<sequence id="sequence_5" name="5" length="100" weight="1.000000" />
<sequence id="sequence_6" name="6" length="100" weight="1.000000" />
<sequence id="sequence_7" name="7" length="100" weight="1.000000" />
<sequence id="sequence_8" name="8" length="100" weight="1.000000" />
<sequence id="sequence_9" name="9" length="100" weight="1.000000" />
<sequence id="sequence_10" name="10" length="100" weight="1.000000" />
<sequence id="sequence_11" name="11" length="100" weight="1.000000" />
<sequence id="sequence_12" name="12" length="100" weight="1.000000" />
<sequence id="sequence_13" name="13" length="100" weight="1.000000" />
<sequence id="sequence_14" name="14" length="100" weight="1.000000" />
<sequence id="sequence_15" name="15" length="100" weight="1.000000" />
<sequence id="sequence_16" name="16" length="100" weight="1.000000" />
<sequence id="sequence_17" name="17" length="100" weight="1.000000" />
<sequence id="sequence_18" name="18" length="100" weight="1.000000" />
<sequence id="sequence_19" name="19" length="100" weight="1.000000" />
<sequence id="sequence_20" name="20" length="100" weight="1.000000" />
<sequence id="sequence_21" name="21" length="100" weight="1.000000" />
<sequence id="sequence_22" name="22" length="100" weight="1.000000" />
<sequence id="sequence_23" name="23" length="100" weight="1.000000" />
<sequence id="sequence_24" name="24" length="100" weight="1.000000" />
<sequence id="sequence_25" name="25" length="100" weight="1.000000" />
<sequence id="sequence_26" name="26" length="100" weight="1.000000" />
<sequence id="sequence_27" name="27" length="100" weight="1.000000" />
<sequence id="sequence_28" name="28" length="100" weight="1.000000" />
<sequence id="sequence_29" name="29" length="100" weight="1.000000" />
<sequence id="sequence_30" name="30" length="100" weight="1.000000" />
<sequence id="sequence_31" name="31" length="100" weight="1.000000" />
<sequence id="sequence_32" name="32" length="100" weight="1.000000" />
<sequence id="sequence_33" name="33" length="100" weight="1.000000" />
<sequence id="sequence_34" name="34" length="100" weight="1.000000" />
<sequence id="sequence_35" name="35" length="100" weight="1.000000" />
<sequence id="sequence_36" name="36" length="100" weight="1.000000" />
<sequence id="sequence_37" name="37" length="100" weight="1.000000" />
<sequence id="sequence_38" name="38" length="100" weight="1.000000" />
<sequence id="sequence_39" name="39" length="100" weight="1.000000" />
<sequence id="sequence_40" name="40" length="100" weight="1.000000" />
<sequence id="sequence_41" name="41" length="100" weight="1.000000" />
<sequence id="sequence_42" name="42" length="100" weight="1.000000" />
<sequence id="sequence_43" name="43" length="100" weight="1.000000" />
<sequence id="sequence_44" name="44" length="100" weight="1.000000" />
<sequence id="sequence_45" name="45" length="100" weight="1.000000" />
<sequence id="sequence_46" name="46" length="100" weight="1.000000" />
<sequence id="sequence_47" name="47" length="100" weight="1.000000" />
<sequence id="sequence_48" name="48" length="100" weight="1.000000" />
<sequence id="sequence_49" name="49" length="100" weight="1.000000" />
<sequence id="sequence_50" name="50" length="100" weight="1.000000" />
<sequence id="sequence_51" name="51" length="100" weight="1.000000" />
<sequence id="sequence_52" name="52" length="100" weight="1.000000" />
<sequence id="sequence_53" name="53" length="100" weight="1.000000" />
<sequence id="sequence_54" name="54" length="100" weight="1.000000" />
<sequence id="sequence_55" name="55" length="100" weight="1.000000" />
<sequence id="sequence_56" name="56" length="100" weight="1.000000" />
<sequence id="sequence_57" name="57" length="100" weight="1.000000" />
<sequence id="sequence_58" name="58" length="100" weight="1.000000" />
<sequence id="sequence_59" name="59" length="100" weight="1.000000" />
<sequence id="sequence_60" name="60" length="100" weight="1.000000" />
<sequence id="sequence_61" name="61" length="100" weight="1.000000" />
<sequence id="sequence_62" name="62" length="100" weight="1.000000" />
<sequence id="sequence_63" name="63" length="100" weight="1.000000" />
<sequence id="sequence_64" name="64" length="100" weight="1.000000" />
<sequence id="sequence_65" name="65" length="100" weight="1.000000" />
<sequence id="sequence_66" name="66" length="100" weight="1.000000" />
<sequence id="sequence_67" name="67" length="100" weight="1.000000" />
<sequence id="sequence_68" name="68" length="100" weight="1.000000" />
<sequence id="sequence_69" name="69" length="100" weight="1.000000" />
<sequence id="sequence_70" name="70" length="100" weight="1.000000" />
<sequence id="sequence_71" name="71" length="100" weight="1.000000" />
<sequence id="sequence_72" name="72" length="100" weight="1.000000" />
<sequence id="sequence_73" name="73" length="100" weight="1.000000" />
<sequence id="sequence_74" name="74" length="100" weight="1.000000" />
<sequence id="sequence_75" name="75" length="100" weight="1.000000" />
<sequence id="sequence_76" name="76" length="100" weight="1.000000" />
<sequence id="sequence_77" name="77" length="100" weight="1.000000" />
<sequence id="sequence_78" name="78" length="100" weight="1.000000" />
<sequence id="sequence_79" name="79" length="100" weight="1.000000" />
<sequence id="sequence_80" name="80" length="100" weight="1.000000" />
<sequence id="sequence_81" name="81" length="100" weight="1.000000" />
<sequence id="sequence_82" name="82" length="100" weight="1.000000" />
<sequence id="sequence_83" name="83" length="100" weight="1.000000" />
<sequence id="sequence_84" name="84" length="100" weight="1.000000" />
<sequence id="sequence_85" name="85" length="100" weight="1.000000" />
<sequence id="sequence_86" name="86" length="100" weight="1.000000" />
<sequence id="sequence_87" name="87" length="100" weight="1.000000" />
<sequence id="sequence_88" name="88" length="100" weight="1.000000" />
<sequence id="sequence_89" name="89" length="100" weight="1.000000" />
<sequence id="sequence_90" name="90" length="100" weight="1.000000" />
<sequence id="sequence_91" name="91" length="100" weight="1.000000" />
<sequence id="sequence_92" name="92" length="100" weight="1.000000" />
<sequence id="sequence_93" name="93" length="100" weight="1.000000" />
<sequence id="sequence_94" name="94" length="100" weight="1.000000" />
<sequence id="sequence_95" name="95" length="100" weight="1.000000" />
<sequence id="sequence_96" name="96" length="100" weight="1.000000" />
<sequence id="sequence_97" name="97" length="100" weight="1.000000" />
<sequence id="sequence_98" name="98" length="100" weight="1.000000" />
<sequence id="sequence_99" name="99" length="100" weight="1.000000" />
<sequence id="sequence_100" name="100" length="100" weight="1.000000" />
<sequence id="sequence_101" name="101" length="100" weight="1.000000" />
<sequence id="sequence_102" name="102" length="100" weight="1.000000" />
<sequence id="sequence_103" name="103" length="100" weight="1.000000" />
<sequence id="sequence_104" name="104" length="100" weight="1.000000" />
<sequence id="sequence_105" name="105" length="100" weight="1.000000" />
<sequence id="sequence_106" name="106" length="100" weight="1.000000" />
<sequence id="sequence_107" name="107" length="100" weight="1.000000" />
<sequence id="sequence_108" name="108" length="100" weight="1.000000" />
<sequence id="sequence_109" name="109" length="100" weight="1.000000" />
<sequence id="sequence_110" name="110" length="100" weight="1.000000" />
<sequence id="sequence_111" name="111" length="100" weight="1.000000" />
<sequence id="sequence_112" name="112" length="100" weight="1.000000" />
<sequence id="sequence_113" name="113" length="100" weight="1.000000" />
<sequence id="sequence_114" name="114" length="100" weight="1.000000" />
<sequence id="sequence_115" name="115" length="100" weight="1.000000" />
<sequence id="sequence_116" name="116" length="100" weight="1.000000" />
<sequence id="sequence_117" name="117" length="100" weight="1.000000" />
<sequence id="sequence_118" name="118" length="100" weight="1.000000" />
<sequence id="sequence_119" name="119" length="100" weight="1.000000" />
<sequence id="sequence_120" name="120" length="100" weight="1.000000" />
<sequence id="sequence_121" name="121" length="100" weight="1.000000" />
<sequence id="sequence_122" name="122" length="100" weight="1.000000" />
<sequence id="sequence_123" name="123" length="100" weight="1.000000" />
<sequence id="sequence_124" name="124" length="100" weight="1.000000" />
<sequence id="sequence_125" name="125" length="100" weight="1.000000" />
<sequence id="sequence_126" name="126" length="100" weight="1.000000" />
<sequence id="sequence_127" name="127" length="100" weight="1.000000" />
<sequence id="sequence_128" name="128" length="100" weight="1.000000" />
<sequence id="sequence_129" name="129" length="100" weight="1.000000" />
<sequence id="sequence_130" name="130" length="100" weight="1.000000" />
<sequence id="sequence_131" name="131" length="100" weight="1.000000" />
<sequence id="sequence_132" name="132" length="100" weight="1.000000" />
<sequence id="sequence_133" name="133" length="100" weight="1.000000" />
<sequence id="sequence_134" name="134" length="100" weight="1.000000" />
<sequence id="sequence_135" name="135" length="100" weight="1.000000" />
<sequence id="sequence_136" name="136" length="100" weight="1.000000" />
<sequence id="sequence_137" name="137" length="100" weight="1.000000" />
<sequence id="sequence_138" name="138" length="100" weight="1.000000" />
<sequence id="sequence_139" name="139" length="100" weight="1.000000" />
<sequence id="sequence_140" name="140" length="100" weight="1.000000" />
<sequence id="sequence_141" name="141" length="100" weight="1.000000" />
<sequence id="sequence_142" name="142" length="100" weight="1.000000" />
<sequence id="sequence_143" name="143" length="100" weight="1.000000" />
<sequence id="sequence_144" name="144" length="100" weight="1.000000" />
<sequence id="sequence_145" name="145" length="100" weight="1.000000" />
<sequence id="sequence_146" name="146" length="100" weight="1.000000" />
<sequence id="sequence_147" name="147" length="100" weight="1.000000" />
<sequence id="sequence_148" name="148" length="100" weight="1.000000" />
<sequence id="sequence_149" name="149" length="100" weight="1.000000" />
<sequence id="sequence_150" name="150" length="100" weight="1.000000" />
<sequence id="sequence_151" name="151" length="100" weight="1.000000" />
<sequence id="sequence_152" name="152" length="100" weight="1.000000" />
<sequence id="sequence_153" name="153" length="100" weight="1.000000" />
<sequence id="sequence_154" name="154" length="100" weight="1.000000" />
<sequence id="sequence_155" name="155" length="100" weight="1.000000" />
<sequence id="sequence_156" name="156" length="100" weight="1.000000" />
<sequence id="sequence_157" name="157" length="100" weight="1.000000" />
<sequence id="sequence_158" name="158" length="100" weight="1.000000" />
<sequence id="sequence_159" name="159" length="100" weight="1.000000" />
<sequence id="sequence_160" name="160" length="100" weight="1.000000" />
<sequence id="sequence_161" name="161" length="100" weight="1.000000" />
<sequence id="sequence_162" name="162" length="100" weight="1.000000" />
<sequence id="sequence_163" name="163" length="100" weight="1.000000" />
<sequence id="sequence_164" name="164" length="100" weight="1.000000" />
<sequence id="sequence_165" name="165" length="100" weight="1.000000" />
<sequence id="sequence_166" name="166" length="100" weight="1.000000" />
<sequence id="sequence_167" name="167" length="100" weight="1.000000" />
<sequence id="sequence_168" name="168" length="100" weight="1.000000" />
<sequence id="sequence_169" name="169" length="100" weight="1.000000" />
<sequence id="sequence_170" name="170" length="100" weight="1.000000" />
<sequence id="sequence_171" name="171" length="100" weight="1.000000" />
<sequence id="sequence_172" name="172" length="100" weight="1.000000" />
<sequence id="sequence_173" name="173" length="100" weight="1.000000" />
<sequence id="sequence_174" name="174" length="100" weight="1.000000" />
<sequence id="sequence_175" name="175" length="100" weight="1.000000" />
<sequence id="sequence_176" name="176" length="100" weight="1.000000" />
<sequence id="sequence_177" name="177" length="100" weight="1.000000" />
<sequence id="sequence_178" name="178" length="100" weight="1.000000" />
<sequence id="sequence_179" name="179" length="100" weight="1.000000" />
<sequence id="sequence_180" name="180" length="100" weight="1.000000" />
<sequence id="sequence_181" name="181" length="100" weight="1.000000" />
<sequence id="sequence_182" name="182" length="100" weight="1.000000" />
<sequence id="sequence_183" name="183" length="100" weight="1.000000" />
<sequence id="sequence_184" name="184" length="100" weight="1.000000" />
<sequence id="sequence_185" name="185" length="100" weight="1.000000" />
<sequence id="sequence_186" name="186" length="100" weight="1.000000" />
<sequence id="sequence_187" name="187" length="100" weight="1.000000" />
<sequence id="sequence_188" name="188" length="100" weight="1.000000" />
<sequence id="sequence_189" name="189" length="100" weight="1.000000" />
<sequence id="sequence_190" name="190" length="100" weight="1.000000" />
<sequence id="sequence_191" name="191" length="100" weight="1.000000" />
<sequence id="sequence_192" name="192" length="100" weight="1.000000" />
<sequence id="sequence_193" name="193" length="100" weight="1.000000" />
<sequence id="sequence_194" name="194" length="100" weight="1.000000" />
<sequence id="sequence_195" name="195" length="100" weight="1.000000" />
<sequence id="sequence_196" name="196" length="100" weight="1.000000" />
<sequence id="sequence_197" name="197" length="100" weight="1.000000" />
<sequence id="sequence_198" name="198" length="100" weight="1.000000" />
<sequence id="sequence_199" name="199" length="100" weight="1.000000" />
<sequence id="sequence_200" name="200" length="100" weight="1.000000" />
<sequence id="sequence_201" name="201" length="100" weight="1.000000" />
<sequence id="sequence_202" name="202" length="100" weight="1.000000" />
<sequence id="sequence_203" name="203" length="100" weight="1.000000" />
<sequence id="sequence_204" name="204" length="100" weight="1.000000" />
<sequence id="sequence_205" name="205" length="100" weight="1.000000" />
<sequence id="sequence_206" name="206" length="100" weight="1.000000" />
<sequence id="sequence_207" name="207" length="100" weight="1.000000" />
<sequence id="sequence_208" name="208" length="100" weight="1.000000" />
<sequence id="sequence_209" name="209" length="100" weight="1.000000" />
<sequence id="sequence_210" name="210" length="100" weight="1.000000" />
<sequence id="sequence_211" name="211" length="100" weight="1.000000" />
<sequence id="sequence_212" name="212" length="100" weight="1.000000" />
<sequence id="sequence_213" name="213" length="100" weight="1.000000" />
<sequence id="sequence_214" name="214" length="100" weight="1.000000" />
<sequence id="sequence_215" name="215" length="100" weight="1.000000" />
<sequence id="sequence_216" name="216" length="100" weight="1.000000" />
<sequence id="sequence_217" name="217" length="100" weight="1.000000" />
<sequence id="sequence_218" name="218" length="100" weight="1.000000" />
<sequence id="sequence_219" name="219" length="100" weight="1.000000" />
<sequence id="sequence_220" name="220" length="100" weight="1.000000" />
<sequence id="sequence_221" name="221" length="100" weight="1.000000" />
<sequence id="sequence_222" name="222" length="100" weight="1.000000" />
<sequence id="sequence_223" name="223" length="100" weight="1.000000" />
<sequence id="sequence_224" name="224" length="100" weight="1.000000" />
<sequence id="sequence_225" name="225" length="100" weight="1.000000" />
<sequence id="sequence_226" name="226" length="100" weight="1.000000" />
<sequence id="sequence_227" name="227" length="100" weight="1.000000" />
<sequence id="sequence_228" name="228" length="100" weight="1.000000" />
<sequence id="sequence_229" name="229" length="100" weight="1.000000" />
<sequence id="sequence_230" name="230" length="100" weight="1.000000" />
<sequence id="sequence_231" name="231" length="100" weight="1.000000" />
<sequence id="sequence_232" name="232" length="100" weight="1.000000" />
<sequence id="sequence_233" name="233" length="100" weight="1.000000" />
<sequence id="sequence_234" name="234" length="100" weight="1.000000" />
<sequence id="sequence_235" name="235" length="100" weight="1.000000" />
<sequence id="sequence_236" name="236" length="100" weight="1.000000" />
<sequence id="sequence_237" name="237" length="100" weight="1.000000" />
<sequence id="sequence_238" name="238" length="100" weight="1.000000" />
<sequence id="sequence_239" name="239" length="100" weight="1.000000" />
<sequence id="sequence_240" name="240" length="100" weight="1.000000" />
<sequence id="sequence_241" name="241" length="100" weight="1.000000" />
<sequence id="sequence_242" name="242" length="100" weight="1.000000" />
<sequence id="sequence_243" name="243" length="100" weight="1.000000" />
<sequence id="sequence_244" name="244" length="100" weight="1.000000" />
<sequence id="sequence_245" name="245" length="100" weight="1.000000" />
<sequence id="sequence_246" name="246" length="100" weight="1.000000" />
<sequence id="sequence_247" name="247" length="100" weight="1.000000" />
<sequence id="sequence_248" name="248" length="100" weight="1.000000" />
<sequence id="sequence_249" name="249" length="100" weight="1.000000" />
<letter_frequencies>
<alphabet_array>
<value letter_id="A">0.293</value>
<value letter_id="C">0.204</value>
<value letter_id="G">0.204</value>
<value letter_id="T">0.293</value>
<value letter_id="c">0.000</value>
<value letter_id="f">0.000</value>
<value letter_id="h">0.000</value>
<value letter_id="m">0.003</value>
<value letter_id="n1">0.003</value>
<value letter_id="n2">0.000</value>
<value letter_id="n3">0.000</value>
<value letter_id="n4">0.000</value>
</alphabet_array>
</letter_frequencies>
</training_set>
<model>
<command_line>meme gataEGca_0.1_250.cytomod.faa.memechip/seqs-centered -oc gataEGca_0.1_250.cytomod.faa.memechip/meme_out -mod zoops -nmotifs 3 -minw 6 -maxw 30 -bfile gataEGca_0.1_250.cytomod.faa.memechip/background -alph gataEGca_0.1_250.cytomod.faa.memechip/alphabet.meme.txt -time 5082 -revcomp -nostatus </command_line>
<host>skat</host>
<type>zoops</type>
<nmotifs>3</nmotifs>
<evalue_threshold>inf</evalue_threshold>
<object_function>E-value of product of p-values</object_function>
<use_llr>0</use_llr>
<min_width>6</min_width>
<max_width>30</max_width>
<wg>11</wg>
<ws>1</ws>
<endgaps>yes</endgaps>
<substring>yes</substring>
<minsites>2</minsites>
<maxsites>250</maxsites>
<wnsites>0.8</wnsites>
<spmap>uni</spmap>
<spfuzz>0.5</spfuzz>
<prior>dirichlet</prior>
<beta>0.01</beta>
<maxiter>50</maxiter>
<distance>1e-05</distance>
<num_sequences>250</num_sequences>
<num_positions>25000</num_positions>
<seed>0</seed>
<ctfrac>-1</ctfrac>
<maxwords>-1</maxwords>
<strands>both</strands>
<priors_file></priors_file>
<reason_for_stopping>Stopped because requested number of motifs (3) found.</reason_for_stopping>
<background_frequencies source="gataEGca_0.1_250.cytomod.faa.memechip/background">
<alphabet_array>
<value letter_id="A">0.295</value>
<value letter_id="C">0.202</value>
<value letter_id="G">0.202</value>
<value letter_id="T">0.295</value>
<value letter_id="c">0.000</value>
<value letter_id="f">0.000</value>
<value letter_id="h">0.000</value>
<value letter_id="m">0.003</value>
<value letter_id="n1">0.003</value>
<value letter_id="n2">0.000</value>
<value letter_id="n3">0.000</value>
<value letter_id="n4">0.000</value>
</alphabet_array>
</background_frequencies>
</model>
<motifs>
<motif id="motif_1" name="GATAmGCA" alt="MEME-1" width="8" sites="13" ic="25.2" re="20.1" llr="181" e_value="3.0e-005" bayes_threshold="11.9685" elapsed_time="100.788000">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">-194</value>
<value letter_id="C">-1035</value>
<value letter_id="G">219</value>
<value letter_id="T">-1035</value>
<value letter_id="c">-1035</value>
<value letter_id="f">-1035</value>
<value letter_id="h">-1035</value>
<value letter_id="m">-1035</value>
<value letter_id="n1">-1035</value>
<value letter_id="n2">-1035</value>
<value letter_id="n3">-1035</value>
<value letter_id="n4">-1035</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">138</value>
<value letter_id="C">-139</value>
<value letter_id="G">-1035</value>
<value letter_id="T">-194</value>
<value letter_id="c">-1035</value>
<value letter_id="f">-1035</value>
<value letter_id="h">-1035</value>
<value letter_id="m">493</value>
<value letter_id="n1">-1035</value>
<value letter_id="n2">-1035</value>
<value letter_id="n3">-1035</value>
<value letter_id="n4">-1035</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1035</value>
<value letter_id="C">-139</value>
<value letter_id="G">-1035</value>
<value letter_id="T">164</value>
<value letter_id="c">-1035</value>
<value letter_id="f">-1035</value>
<value letter_id="h">-1035</value>
<value letter_id="m">-1035</value>
<value letter_id="n1">-1035</value>
<value letter_id="n2">-1035</value>
<value letter_id="n3">-1035</value>
<value letter_id="n4">-1035</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">164</value>
<value letter_id="C">-139</value>
<value letter_id="G">-1035</value>
<value letter_id="T">-1035</value>
<value letter_id="c">-1035</value>
<value letter_id="f">-1035</value>
<value letter_id="h">-1035</value>
<value letter_id="m">-1035</value>
<value letter_id="n1">-1035</value>
<value letter_id="n2">-1035</value>
<value letter_id="n3">-1035</value>
<value letter_id="n4">-1035</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1035</value>
<value letter_id="C">-1035</value>
<value letter_id="G">-1035</value>
<value letter_id="T">-1035</value>
<value letter_id="c">-1035</value>
<value letter_id="f">-1035</value>
<value letter_id="h">-1035</value>
<value letter_id="m">863</value>
<value letter_id="n1">-1035</value>
<value letter_id="n2">-1035</value>
<value letter_id="n3">-1035</value>
<value letter_id="n4">-1035</value>
</alphabet_array>